
dataTranslation = {
    "Click the Logo on left to close/open the description.": "点击左侧Logo图片来关闭与打开此说明",
    "Show picture in box.": "在方框中显示图片",
    "Difficulty Level": "难度",
    "standard": "普通",
    "difficult": "困难",
    "Input and fixed": "输入后定位",
    "clear fixing": "清除固定",
    "Drag to move image, wheel or two fingers to zoom in or out.": "按住拖动可以上下左右拖动画面，用鼠标滚轮或双指可以放大缩小画面。",
    "Show the technology when hovering on a block.": "鼠标或手指放在某个方块中，将会显示这个方块的前置后置等科技。",
    "Input an exactly name in the input box to fix a item in center.": "在上方输入准确名称后将会固定选择这个建筑或工具并移动画面将其放在中央。输入一个字后会有下拉选择（QQ自带的浏览器不行，只会弹警告）。",
    "Color": "颜色",
    "Red": "红色",
    "Required": "硬性需求",
    "Dash": "虚线",
    "need its craft": "建造时材料的隐性需求",
    "Cyan": "天蓝色",
    "upgrade from": "由此升级而来",
    "Blue": "蓝色",
    "upgrade to": "可升级成",
    "Green": "绿色",
    "unlock": "可解锁",
    "Ruins of Light": "光明遗迹",
    "Location": "位于",
    "Forest Entrance": "森林入口",
    "Desolate Meadow": "寂寞的草原",
    "Everblue Lake": "不干涸的湖水",
    "Dense Jungle": "茂密的森林",
    "Cold Terrain": "寒冷的大地",
    "Ancient Mine F1": "古代的矿山 1层",
    "Frozen Hill": "冰冷的小丘",
    "Burning Canyon": "燃烧的峡谷",
    "Sealed Land": "被封印的土地",
    "Earth Spirit's Cave": "土地精灵的洞穴（奇怪的洞穴）",
    "Dwarf Ruins F6": "矮人遗迹 6层",
    "Dark Cave": "黑暗洞穴",

    "Campfire": "篝火",
    "Fire Pit": "炭炉",
    "Canopy": "凉棚",
    "Straw Hut": "草窝棚",
    "Shack": "窝棚",
    "Straw Pile Bed": "草堆床",
    "Cot": "简易床",
    "Wooden Bed": "木床",
    "Hammock": "吊床",
    "Leather Hut": "皮窝棚",
    "Apprentice's Desk": "实习生的书桌",
    "Archwizard's Desk": "熟练魔法师的书桌",
    "Meditation Study": "冥想的书斋",
    "Magic Torch": "魔法火炬",
    "Indoor Oil Lamp": "室内灯盏",
    "Indoor Oven": "室内炭炉",
    "Smoker": "熏制炭炉",
    "Foundry": "熔炉",
    "Wind Foundry": "风力熔炉",
    "Cooking Oven": "料理炭炉",
    "Kiln": "大锅",
    "Storage Pot": "保管坛子",
    "Refrigerated Pot": "冷冻坛子",
    "Barrel": "酒桶",
    "Cheese Ripener": "奶酪发酵机",
    "Fermented Jar": "发酵罐子",
    "Jerky Dryer": "肉脯干燥台",
    "Juicer": "榨汁机",
    "Basket": "篮子",
    "Wooden Box": "木箱子",
    "Sturdy Box": "坚固的箱子",
    "Safe": "金库",
    "Safe of Magic": "魔法金库",
    "Storage": "仓库",
    "Bathroom": "卫生间",
    "Garden": "园地",
    "Mound of Fertilizer": "肥料堆",
    "Fence": "栅栏",
    "Strong Fence": "结实的栅栏",
    "Fence Door": "栅栏之门",
    "Strong Fence Door": "结实的栅栏之门",
    "Fish Trap": "鱼篓",
    "Groundwater Pump": "地下水泵",
    "Water Purifier": "净水器",
    "Mannequin": "模特道具",
    "Mountain Goat Pen": "山羊圈",
    "Pet Crate": "宠物窝",
    "Raft": "木筏",
    "Stone Road": "石路",

    "Work Bench": "工作台",
    "Armor Bench": "防具制作台",
    "Weapon Bench": "武器制作台",
    "Battle Scarecrow": "战斗稻草人",
    "Taunting Scarecrow": "挑衅稻草人",
    "Pumpkin Scarecrow": "南瓜稻草人",
    "Tree Stump": "树根",

    "Tanning Bench": "软化工作台",
    "Weaver": "纺织机",
    "Alchemist's Pot": "炼金术士的锅",
    "Alchemy EQPT": "炼金术实验工具",
    "Lightning Rod": "避雷针",
    "Power Controller": "魔力控制装置",
    "Magic EQPT Bench": "魔法装备制作台",
    "Auto Repair Exhibit": "自动修理展示台",
    "Black Magical Anvil": "黑魔法铁砧",
    "Human Cannon": "人体大炮",
    "Portal Exit": "时空的出口",
    "Spacetime Rift": "时空裂痕",
    "Strange Magical Symbol": "奇怪的魔法图案",
    "Ancient Mythril Forge": "古代秘银铁匠铺",
    "Egg Incubator": "蛋孵化器",

    "Light Tablet": "光明碑牌",
    "Dimensional Tablet": "次元碑牌",
    "Flint": "火石",
    "Branch": "树枝",
    "Bush": "草丛",
    "Log": "原木",
    "Rock": "岩石",
    "Clay": "黏土",
    "Machinery": "机器装置",
    "Rope": "绳子",
    "Stone": "石材",
    "Charcoal": "木炭",
    "Brick": "砖头",
    "Parchment": "羊皮纸",
    "Linen": "亚麻布",
    "Cobweb Thread": "蜘蛛丝线",
    "Lasso": "套索",
    "Leather Strap": "皮绳",
    "Magic Branch": "魔法枝头",

    "Hemp": "亚麻",
    "Pixie Dust": "仙子尘",
    "Apple Branch": "苹果树枝",
    "Oak Branch": "橡树枝",
    "Old Branch": "古木树枝",
    "Spider Cocoon": "蜘蛛茧",
    "Beehive": "蜂窝",
    "Icecap": "冰松",

    "Beast's Grass": "猛兽的草",
    "Fire Herb": "火焰草",
    "Pumpkin": "南瓜",
    "Ghost Mushroom": "幽灵蘑菇",

    "Hide": "整张皮",
    "Tough Hide": "硬邦邦的整张皮",
    "Tough Leather": "硬邦邦的皮",
    "Fur": "毛皮",
    "Leather": "皮",
    "Wool": "绒毛",
    "Snake Fang": "蛇犬齿",
    "Snake Leather": "蛇皮",
    "Monster Bird Beak": "怪鸟嘴",
    "Feather": "羽毛",
    "Fish Fin Fragment": "鳍碎片",
    "Snow Totem Decor": "眼睛图腾装饰",
    "Rock Monster Debris": "石怪残骸",
    "Basilisk Leather": "蛇怪皮",
    "Flaming Magic Heart": "炽热的魔法心脏",
    "Strange Symbol Map Fragment": "奇怪图案的地图碎片",

    "Sulfur": "硫磺",
    "Dark Element": "黑暗元素",
    "Earth Element": "土地元素",
    "Mana Mote": "法力浮尘",
    "Mana Crystal": "法力结晶",
    "Steel Ore": "铁矿石",
    "Silver Ore": "银矿石",
    "Gold Ore": "金矿石",
    "Platinum Ore": "白金矿石",
    "Mythril Ore": "秘银矿石",
    "Mercury Ore": "水银矿石",
    "Iron Bar": "铁铸锭",
    "Steel Bar": "钢铁铸锭",
    "Silver Bar": "银铸锭",
    "Gold Bar": "金铸锭",
    "Platinum Bar": "白金铸锭",
    "Mythril Bar": "秘银铸锭",
    "Earth Steel Bar": "大地钢铁铸锭",
    "Black Cast Iron Bar": "黑色生铁铸锭",
    "Mercury": "水银",

    "Torch": "火炬",
    "Straw Sleeping Bag": "草屑睡袋",
    "Thick Sleeping Bag": "厚重睡袋",
    "Frost Stone": "含有寒气的石头",
    "Magic Handwarmer": "魔法暖手宝",
    "Multipurpose Cooler Bag": "万能保温袋",
    "Cooking Pot": "料理汤锅",
    "Simple Tent": "简易帐篷",
    "Carrier": "背架",
    "Backpack": "睡袋",
    "Small Backpack": "小型背包",
    "Small Bag": "小型包",
    "Bandage": "绷带",
    "First-aid Bandage": "急救绷带",
    "Bear Trap": "捕熊器",
    "Crude Pouch": "粗糙的口袋",
    "Incantation Bag": "咒书包",
    "Alchemy Bag": "炼金术包",
    "Dynamite": "炸药",
    "Fertilizer": "肥料",
    "Repair Hammer": "修理锤子",
    "Repair Kit for Metal, Wood": "金属，木材维修套装",
    "Repair Kit for Cloth, Leather": "布，皮制维修套装",
    "Empty Water Bag": "空水袋",

    "Map Piece": "地图碎片",

    "Stone Axe": "石斧",
    "Stone Knife": "采集用石刀",
    "Stone Pickaxe": "石镐",
    "Shovel": "铲子",
    "Lumberjack Axe": "伐木斧",
    "Hand Axe": "手斧",
    "Pickaxe": "镐头",
    "Black Iron Pickaxe": "黑色铁镐",
    "Fishing Pole": "鱼竿",
    "Wooden Spear": "木矛",
    "Crude Staff": "粗糙的拐杖",
    "Hunting Bow": "狩猎弓箭",
    "Wooden Arrow": "木箭",
    "Stone Arrow": "石箭",

    "Wool Clothes": "羊绒衣",

};
