
dataTranslation = {
    "Technology tree of The wild darkness": "《The wild darkness》科技樹",
    "Click the Logo on left to close/open the description.": "點擊左側Logo圖案以關閉或開啟此說明",
    "Show images for Structures and Items": "顯示建筑与物品的影像",
    "Difficulty Level": "難度",
    "standard": "普通",
    "difficult": "困難",
    "Input and fixed": "輸入後定位",
    "clear fixing": "解除固定",
    "Drag to move image, wheel or two fingers to zoom in or out.": "按住可以上下左右拖動畫面，滑鼠滾輪或雙指可以放大縮小畫面。",
    "Show the technology when hovering on a block.": "滑鼠或手指放在某個方塊內，將會顯示此方塊的前置後置等。",
    "Input an exactly name in the input box to fix a item in center.": "在上方输入准确名称后将会固定选择这个建筑或工具并移动画面将其放在中央。输入一个字后会有下拉选择（QQ自带的浏览器不行，只会弹警告）。",
    "Color": "顏色",
    "Red": "紅色",
    "Required": "硬性需求",
    "Dash": "虛線",
    "need its craft": "因為材料的隱性需求",
    "Cyan": "天藍色",
    "upgrade from": "由此升級而來",
    "Blue": "藍色",
    "upgrade to": "可升級到",
    "Green": "綠色",
    "unlock": "可解鎖",
    "Ruins of Light": "光明遺蹟",
    "Location": "位於",
    "Forest Entrance": "森林入口",
    "Desolate Meadow": "寂寞的草原",
    "Everblue Lake": "不乾涸的湖水",
    "Dense Jungle": "茂密的森林",
    "Cold Terrain": "寒冷的大地",
    "Ancient Mine F1": "古代的礦山 1層",
    "Frozen Hill": "冰冷的小丘",
    "Burning Canyon": "燃燒的峽谷",
    "Sealed Land": "被封印的土地",
    "Earth Spirit's Cave": "土地精靈的洞穴（奇怪的洞穴）",
    "Dwarf Ruins F6": "矮人遺蹟 6層",
    "Dark Cave": "黑暗洞穴",

    "Campfire": "篝火",
    "Fire Pit": "炭爐",
    "Canopy": "涼棚",
    "Straw Hut": "草窩棚",
    "Shack": "窩棚",
    "Straw Pile Bed": "草堆床",
    "Cot": "簡易床",
    "Wooden Bed": "木床",
    "Hammock": "吊床",
    "Leather Hut": "皮窩棚",
    "Apprentice's Desk": "實習生的書桌",
    "Archwizard's Desk": "熟練魔法師的書桌",
    "Meditation Study": "冥想的書齋",
    "Magic Torch": "魔法火炬",
    "Indoor Oil Lamp": "室內燈盞",
    "Indoor Oven": "室內炭爐",
    "Smoker": "燻製炭爐",
    "Foundry": "熔爐",
    "Wind Foundry": "風力熔爐",
    "Cooking Oven": "料理炭爐",
    "Kiln": "大鍋",
    "Storage Pot": "保管壇子",
    "Refrigerated Pot": "冷凍壇子",
    "Barrel": "酒桶",
    "Cheese Ripener": "奶酪發酵機",
    "Fermented Jar": "發酵罐子",
    "Jerky Dryer": "肉舖乾燥台",
    "Juicer": "榨汁機",
    "Basket": "籃子",
    "Wooden Box": "木箱子",
    "Sturdy Box": "堅固的箱子",
    "Safe": "金庫",
    "Safe of Magic": "魔法金庫",
    "Storage": "倉庫",
    "Bathroom": "衛生間",
    "Garden": "園地",
    "Mound of Fertilizer": "肥料堆",
    "Fence": "柵欄",
    "Strong Fence": "結實的柵欄",
    "Fence Door": "柵欄之門",
    "Strong Fence Door": "結實的柵欄之門",
    "Fish Trap": "魚簍",
    "Groundwater Pump": "地下水泵浦",
    "Water Purifier": "淨水器",
    "Mannequin": "模特道具",
    "Mountain Goat Pen": "山羊圈",
    "Pet Crate": "寵物窩",
    "Raft": "木筏",
    "Stone Road": "石路",

    "Work Bench": "工作台",
    "Armor Bench": "防具製作台",
    "Weapon Bench": "武器製作台",
    "Battle Scarecrow": "戰鬥稻草人",
    "Taunting Scarecrow": "挑釁稻草人",
    "Pumpkin Scarecrow": "南瓜稻草人",
    "Tree Stump": "樹根",

    "Tanning Bench": "軟化工作台",
    "Weaver": "紡織機",
    "Alchemist's Pot": "煉金術士的鍋",
    "Alchemy EQPT": "煉金術實驗工具",
    "Lightning Rod": "避雷針",
    "Power Controller": "魔力控制裝置",
    "Magic EQPT Bench": "魔法裝備製作台",
    "Auto Repair Exhibit": "自動修理展示台",
    "Black Magical Anvil": "黑魔法鐵砧",
    "Human Cannon": "人體大砲",
    "Portal Exit": "時空的出口",
    "Spacetime Rift": "時空裂痕",
    "Strange Magical Symbol": "奇怪的魔法圖案",
    "Ancient Mythril Forge": "古代秘銀鐵匠鋪",
    "Egg Incubator": "蛋孵化器",
    "Abyss of Dream's machine": "夢之深淵機器",
    "Debris of nightmares": "惡夢碎片",

    "Light Tablet": "光明碑牌",
    "Dimensional Tablet": "次元碑牌",
    "Flint": "火石",
    "Branch": "樹枝",
    "Bush": "草叢",
    "Log": "原木",
    "Rock": "岩石",
    "Clay": "黏土",
    "Machinery": "機器裝置",
    "Rope": "繩子",
    "Stone": "石材",
    "Charcoal": "木炭",
    "Brick": "磚頭",
    "Parchment": "羊皮紙",
    "Linen": "亞麻布",
    "Cobweb Thread": "蜘蛛絲線",
    "Lasso": "套索",
    "Leather Strap": "皮繩",
    "Magic Branch": "魔法枝頭",

    "Hemp": "亞麻",
    "Pixie Dust": "仙子塵",
    "Apple Branch": "蘋果樹枝",
    "Oak Branch": "橡樹枝",
    "Old Branch": "古木樹枝",
    "Spider Cocoon": "蜘蛛繭",
    "Beehive": "蜂窩",
    "Icecap": "冰松",

    "Beast's Grass": "猛獸的草",
    "Fire Herb": "火焰草",
    "Pumpkin": "南瓜",
    "Ghost Mushroom": "幽靈蘑菇",

    "Hide": "整張皮",
    "Tough Hide": "硬邦邦的整張皮",
    "Tough Leather": "硬邦邦的皮",
    "Fur": "毛皮",
    "Leather": "皮",
    "Wool": "絨毛",
    "Snake Fang": "蛇犬齒",
    "Snake Leather": "蛇皮",
    "Monster Bird Beak": "怪鳥嘴",
    "Feather": "羽毛",
    "Fish Fin Fragment": "鰭碎片",
    "Snow Totem Decor": "眼睛圖騰裝飾",
    "Rock Monster Debris": "石怪殘骸",
    "Basilisk Leather": "蛇怪皮",
    "Flaming Magic Heart": "熾熱的魔法心臟",
    "Strange Symbol Map Fragment": "奇怪圖案的地圖碎片",

    "Sulfur": "硫磺",
    "Dark Element": "黑暗元素",
    "Earth Element": "土地元素",
    "Mana Mote": "法力浮塵",
    "Mana Crystal": "法力結晶",
    "Steel Ore": "鐵礦石",
    "Silver Ore": "銀礦石",
    "Gold Ore": "金礦石",
    "Platinum Ore": "白金礦石",
    "Mythril Ore": "秘銀礦石",
    "Mercury Ore": "水銀礦石",
    "Iron Bar": "鐵鑄錠",
    "Steel Bar": "鋼鐵鑄錠",
    "Silver Bar": "銀鑄錠",
    "Gold Bar": "金鑄錠",
    "Platinum Bar": "白金鑄錠",
    "Mythril Bar": "秘銀鑄錠",
    "Earth Steel Bar": "大地鋼鐵鑄錠",
    "Black Cast Iron Bar": "黑色生鐵鑄錠",
    "Mercury": "水銀",

    "Torch": "火炬",
    "Straw Sleeping Bag": "草屑睡袋",
    "Thick Sleeping Bag": "厚重睡袋",
    "Frost Stone": "含有寒氣的石頭",
    "Magic Handwarmer": "魔法暖手寶",
    "Multipurpose Cooler Bag": "萬能保溫袋",
    "Cooking Pot": "料理湯鍋",
    "Simple Tent": "簡易帳篷",
    "Carrier": "背架",
    "Backpack": "睡袋",
    "Small Backpack": "小型背包",
    "Small Bag": "小型包",
    "Bandage": "繃帶",
    "First-aid Bandage": "急救繃帶",
    "Bear Trap": "捕熊器",
    "Crude Pouch": "粗糙的口袋",
    "Incantation Bag": "咒書包",
    "Alchemy Bag": "煉金術包",
    "Dynamite": "炸藥",
    "Fertilizer": "肥料",
    "Repair Hammer": "修理錘子",
    "Repair Kit for Metal, Wood": "金属，木材維修套裝",
    "Repair Kit for Cloth, Leather": "布，皮制維修套裝",
    "Empty Water Bag": "空水袋",

    "Map Piece": "地圖碎片",

    "Stone Axe": "石斧",
    "Stone Knife": "採集用石刀",
    "Stone Pickaxe": "石鎬",
    "Shovel": "鏟子",
    "Lumberjack Axe": "伐木斧",
    "Hand Axe": "手斧",
    "Pickaxe": "鎬頭",
    "Black Iron Pickaxe": "黑色鐵鎬",
    "Fishing Pole": "魚竿",
    "Wooden Spear": "木矛",
    "Crude Staff": "粗糙的拐杖",
    "Hunting Bow": "狩獵弓箭",
    "Wooden Arrow": "木箭",
    "Stone Arrow": "石箭",

    "Wool Clothes": "羊絨衣",

};
